### ISSUE TITLE
Hello, i have a question .. 

### ISSUE THREAD

**Issue by jjunyjjuny** [Leopold-V/react-parcel-app#1]
hello, I am a student studying programming.
I looked up your blog to make my own CRA. 
My boilerplate is installable with npx on mac, but on windows it gives me an error.
As a result of looking for the cause, it seems that the command to run as "Node" was not specified when running create-app.js. 

How did you solve this problem?

Your project can be installed with npx in both Mac and Windows environments. but my project is only on mac.

The Facebook CRA team specified the node environment via the scripts field in package.json, but you didn't.

How is that possible? Did you process it in the file registered in .gitignore?
I would really appreciate it if you could reply. Have a nice day!

[here](https://github.com/jjunyjjuny/react-typescript-boilerplate) is my project repo!!

**Comment by Leopold-V** [comment]
Hey, what error did you get exactly ?

I am using windows and i tested to install your project and it works !

So i guess something else is wrong, what version of node and npm are you using ?

**Comment by jjunyjjuny** [comment]
first, thanks to answer! 

and.... what??? you can install my project using "npx create-dd-app projectName"?????

I'm also using windows and I can install your project, but my project can't. why.............

p.s


When I tried it with a friend who used Windows a while ago, it installed well. 

OMG ...  I think there is something wrong with my local environment !!!!!!!!!!!!!!!!!!!!!! 

I've run "npm audit fix --force" before. After that, sometimes this screen pops up. I think this is the problem.
Thank you for answer!!

![image](https://user-images.githubusercontent.com/41738385/121687589-7eee1180-cafd-11eb-95f7-4e13035fed4a.png)


----------------------

Let me explain the error first.

I put the "generate-app.js" file in the root directory and set the "bin" field of "package.json" to 

```
"bin" : {
"create-dd-app": './generate-app.js "
}
``` 

and install it with npx When I tried, I got this error:

![error](https://user-images.githubusercontent.com/41738385/121681349-ab059480-caf5-11eb-8a20-a620d46001ad.PNG)

oh sorry, this is Korean.. 

Below, I am attaching an English error for the same situation I found on stackoverflow.
![image](https://user-images.githubusercontent.com/41738385/121681796-31ba7180-caf6-11eb-891e-fffcebfbcb97.png)


my version 
Node v14.17.0
npm 7.11.1

**Comment by jjunyjjuny** [comment]
And, put the generate-app.js file in bin folder and package.json into 

```
"bin": {
"create-dd-app": "./bin/generate-app.js"
}
```
an error stating that the path to r cannot be found occurs.

I tried installing my package globally and it worked fine.

> $ npm i -g create-dd-app 
> $ create-dd-app projectName  // it work on windows 

Error only when trying to install with npx on windows

> $ npx create-dd-app projectName // ok on mac, BUT error on windows


---------------------------------

My guess is, 

> #! /usr/bin/env node

- This shebang line only works on Mac (Unix to be exact). windows ignore this

- so, windows read this file by JScritps 

- but JScripts are used in the browser. error! 

- I have to command that file to be read into node by using package.json scripts

- like this 

```
"scripts" : {
  "generate" : "node generate-app.js" 
}
```

- but, you didn`t!
- but, it works fine!!! why!?!?

**Comment by Leopold-V** [comment]
Yea it works fine for me to install your project on windows so that's not related to your project code and config. Also there is no need to modify the scripts field, npx only execute the file in the /bin path.

As you say I think there is something wrong with your local environnement. 

Did you try to install other boilerplate with npx like "npx create-react-app"  to see if it does works ?
If it doesn't then there is a high chance it is about your env path and stuffs on your windows that are wrong.

**Comment by jjunyjjuny** [comment]
I can install npx create-react-app. 

I'll list what I've found so far.

1. in my local, "npx react-parcel-app" is work
2. in my local, "npx create-dd-app" is not work / error host scripts

so, I check my js file, and find it 
![image](https://user-images.githubusercontent.com/41738385/121696488-16a42d80-cb07-11eb-91f3-e0417e600314.png)
(sorry, not english ...)

'연결 프로그램' is "Opens with" in English.
I thought this was a problem, so I changed it to vscode, and try "npx create-dd-app"
Then no error occurred! BUT just open 'generate-app.js'. not excute
Even if "open withs" was a problem, it doesn't explain how "npx react-parcel-app" works.........

![image](https://user-images.githubusercontent.com/41738385/121697163-bfeb2380-cb07-11eb-871f-48eaef294d4a.png)

Then I changed it to node and tried running it.
![image](https://user-images.githubusercontent.com/41738385/121699767-2e30e580-cb0a-11eb-9920-0d1ece5bd561.png)

![image](https://user-images.githubusercontent.com/41738385/121700033-76500800-cb0a-11eb-8dec-4fba1f22890a.png)

occurred other!!! Upon closer inspection, a miss named "require" was found. However, this miss was discovered and resolved before. In other words, it seems to load some cached data!!

---- 

I found the cause!! That's the npx cache!! 

![cache](https://user-images.githubusercontent.com/41738385/121732010-a3151700-cb2c-11eb-9d83-45b7f3cd22c2.PNG)

This image is blank because I deleted it and captured it. 
Before i deleted them there was a cache saved the first time i ran with npx.

and in my local, "npx create-dd-app" is work!

**Comment by Leopold-V** [comment]
Hi, oh I'm glad you fix your problem, react-parcel-app works as any others boilerplates, thanks to npx and the script in bin folder. I was a bit out of idea on this one! But cool if that is resolved because of your npm cache i will close the issue.
